apiVersion: v1
kind: Service
metadata:
  name: emoji-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: emoji
    version: blue # This can be changed to "green" when switching traffic
